schema_version: 1

context:
  version: "2026.9.0"

package:
  name: pyadjoint
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyadjoint-ad/pyadjoint_ad-${{ version }}.tar.gz
  sha256: dd5ff4bd68c3be5f844cbbbad42c6fc9b75d68aa15a49f9c069886bc6df52571

build:
  number: 0
  noarch: python
  script:
    content: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.2
    - pip
  run:
    - python >=${{ python_min }}
    - scipy >=1.0
    - sympy
    - checkpoint-schedules

tests:
  - python:
      imports:
        - pyadjoint
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Algorithmic differentiation framework for DOLFINx.
  license: LGPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/dolfin-adjoint/pyadjoint

extra:
  recipe-maintainers:
    - finsberg
    - jorgensd
